In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import tensorflow as tf

tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/My Drive/Kaggle"

# /content/gdrive/My Drive/Kaggle is the path where kaggle.json is present in the Google Drive

In [ ]:
#changing the working directory

%cd /content/gdrive/My Drive/Kaggle

/content/gdrive/My Drive/Kaggle


In [ ]:
% pwd

#Check the present working directory using pwd command

'/content/gdrive/My Drive/Kaggle'

In [ ]:
!kaggle competitions files crowdflower-search-relevance

name                      size  creationDate         
------------------------  ----  -------------------  
test.csv.zip               5MB  2018-05-11 23:43:21  
train.csv.zip              2MB  2018-05-11 23:43:21  
sampleSubmission.csv.zip  51KB  2018-05-11 23:43:21  


In [ ]:
!kaggle competitions download crowdflower-search-relevance -f train.csv.zip

  0% 0.00/1.87M [00:00<?, ?B/s]
100% 1.87M/1.87M [00:00<00:00, 31.0MB/s]


In [ ]:
!ls

Apple-Twitter-Sentiment-DFE.csv    saved_models       train.csv.zip
apple-twitter-sentiment-texts.csv  submission.csv     train_embed_df.csv
kaggle.json			   test.csv.zip       train-sample.csv.zip
sampleSubmission.csv		   test_embed_df.csv  train.tsv
sampleSubmission.csv.zip	   test.tsv	      train_v2.csv
sampleSubmission_v2.csv.zip	   train.csv	      tweets_labelled.csv


In [ ]:
#unzipping the zip files and deleting the zip files

!unzip -o \train.csv.zip  && rm train.csv.zip

# !unzip -o \test.csv.zip  && rm test.csv.zip

Archive:  train.csv.zip
  inflating: train.csv               


In [ ]:
# import pandas as pd

# df_test = pd.read_csv('test.csv')
# df_test.head()

In [ ]:
import pandas as pd

df = pd.read_csv("train.csv")
df.head()

id                      query  ... median_relevance relevance_variance
0   1  bridal shower decorations  ...                1              0.000
1   2       led christmas lights  ...                4              0.000
2   4                  projector  ...                4              0.471
3   5                  wine rack  ...                4              0.000
4   7                 light bulb  ...                2              0.471

[5 rows x 6 columns]

In [ ]:
df.shape

(10158, 6)

In [ ]:
# Pre-processing
# We will remove all nan entries in our train dataset

print(df.isnull().sum())

id                        0
query                     0
product_title             0
product_description    2444
median_relevance          0
relevance_variance        0
dtype: int64


In [ ]:
# df = df.dropna()

df["product_description"] = df["product_description"].fillna(df["product_title"])

In [ ]:
df.head()

id                      query  ... median_relevance relevance_variance
0   1  bridal shower decorations  ...                1              0.000
1   2       led christmas lights  ...                4              0.000
2   4                  projector  ...                4              0.471
3   5                  wine rack  ...                4              0.000
4   7                 light bulb  ...                2              0.471

[5 rows x 6 columns]

In [ ]:
df.shape

(10158, 6)

In [ ]:
print(df.loc[1, 'query'])
print(df.loc[1, 'product_title'])
print(df.loc[1, 'product_description'])
print(df.loc[1, 'median_relevance'])

led christmas lights
Set of 10 Battery Operated Multi LED Train Christmas Lights - Clear Wire
Set of 10 Battery Operated Train Christmas Lights Item #X124210 Features: Color: multi-color bulbs with matching train light covers / clear wire Multi-color consists of red, green, blue and yellow bulbs Number of bulbs on string: 10 Bulb size: micro LED Spacing between bulbs: 6 inches Lighted length: 4.5 feet Total length: 5.5 feet 12 inch lead cord Additional product features: LED lights use 90% less energy Cool to the touch If one bulb burns out, the rest will stay lit Lights are equipped with Lamp Lock feature, which makes them replaceable, interchangeable and keeps them from falling out Requires 3 "AA" batteries (not included) Convenient on/off/timer switch located on battery pack Timer function on battery pack allows for 6 hours on and 18 hours off Cannot connect multiple sets together UL listed for indoor use only Train dimensions: 1.5"H x 1.8"W x .5"D Material(s): plastic/wire/acrylic
4

In [ ]:
print(df.loc[12, 'query'])
print(df.loc[12, 'product_title'])
print(df.loc[12, 'product_description'])
print(df.loc[12, 'median_relevance'])

led christmas lights
Set of 10 Battery Operated Train Christmas Lights Item #X124210 Features: Color: multi-color bulbs with matching train light covers / clear wire Multi-color consists of red, green, blue and yellow bulbs Number of bulbs on string: 10 Bulb size: micro LED Spacing between bulbs: 6 inches Lighted length: 4.5 feet Total length: 5.5 feet 12 inch lead cord Additional product features: LED lights use 90% less energy Cool to the touch If one bulb burns out, the rest will stay lit Lights are equipped with Lamp Lock feature, which makes them replaceable, interchangeable and keeps them from falling out Requires 3 "AA" batteries (not included) Convenient on/off/timer switch located on battery pack Timer function on battery pack allows for 6 hours on and 18 hours off Cannot connect multiple sets together UL listed for indoor use only Train dimensions: 1.5"H x 1.8"W x .5"D Material(s): plastic/wire/acrylic
4


In [ ]:
print(df.loc[23, 'query'])
print(df.loc[23, 'product_title'])
print(df.loc[23, 'product_description'])
print(df.loc[23, 'median_relevance'])

projector
ViewSonic Pro8200 DLP Multimedia Projector
4


In [ ]:
print(df.loc[144, 'query'])
print(df.loc[144, 'product_title'])
print(df.loc[144, 'product_description'])
print(df.loc[144, 'median_relevance'])

wine rack
Like a silent and sturdy tree, the Southern Enterprises Bird and Branch Coat Rack is an eye-catching addition to your home décor. This tree themed coat rack features strong branches with pinecone accents and a small bird perched at the top to give it a whimsical and welcoming appearance while still making it sturdy enough to hold your coats, hats, umbrellas and more. Whether it serves as a coat rack, a hat rack or a combination of the two, it’ll be a great space saver that gets appreciated for its graceful appearance.
Number of Hooks: 10
Frame Material: Metal
Hardware Material: Metal
Dimensions: 69.5 " H x 13.25 " W x 13.25 " D
Weight: 12.0 Lb.
Assembly Details: assembly required
4


In [ ]:
pd.set_option('display.max_colwidth', None)

In [ ]:
# Labels in our dataset

# 1 to 4 -> 1 being the item does not satisfy our search query and 4 being the item completely satisfies our search query

In [ ]:
print('Train target distribution')

print(df.median_relevance.value_counts())

Train target distribution
4    6171
3    1737
2    1476
1     774
Name: median_relevance, dtype: int64


In [ ]:
!pip install sentence-transformers

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-mpnet-base-v2')

In [ ]:
query_embed = model.encode(df['query'].to_numpy())
print(query_embed)

[[ 0.00926366 -0.08032771 -0.01508144 ...  0.0173768   0.00115655
   0.02382405]
 [-0.03399246  0.00466795 -0.04888829 ...  0.03406521  0.02907829
  -0.01106864]
 [-0.01177649 -0.00507039  0.01180198 ... -0.0031324  -0.04806018
  -0.00681518]
 ...
 [ 0.05859424 -0.02421954 -0.00885277 ... -0.00799452 -0.06081662
   0.00053554]
 [ 0.00327841 -0.08907936 -0.03979023 ...  0.01395799  0.05264618
  -0.02527668]
 [-0.02924857 -0.09371798 -0.0364729  ... -0.02349585 -0.04016004
   0.00919867]]


In [ ]:
product_title_embed = model.encode(df['product_title'].to_numpy())
print(product_title_embed)

[[ 0.0566823  -0.05644972 -0.02455119 ...  0.00628823 -0.00167799
   0.00429321]
 [-0.0200483  -0.00431843 -0.01329643 ...  0.00359729 -0.00215817
   0.02442659]
 [ 0.00472137  0.03564146  0.00489547 ...  0.00522444 -0.04584635
   0.02316347]
 ...
 [-0.0508812   0.03558285 -0.00222277 ...  0.0203123  -0.03450305
   0.01762916]
 [ 0.06492424 -0.07047806  0.02215762 ... -0.00021466 -0.03016381
  -0.00063721]
 [ 0.00127713 -0.09816678 -0.01356772 ... -0.01252668 -0.04370638
  -0.00264896]]


In [ ]:
product_description_embed = model.encode(df['product_description'].to_numpy())
print(product_description_embed)

[[ 0.02629645 -0.07776    -0.00164363 ...  0.01986052 -0.00685553
  -0.02263863]
 [-0.01048018 -0.03571871 -0.00926889 ...  0.04563279  0.00325655
  -0.02427218]
 [ 0.00472137  0.03564146  0.00489547 ...  0.00522444 -0.04584635
   0.02316347]
 ...
 [-0.04229704  0.05174326 -0.00296191 ...  0.03708468  0.00471096
   0.01799529]
 [ 0.04905127 -0.11287799 -0.0087634  ... -0.00074117  0.00744993
  -0.01963961]
 [ 0.00127713 -0.09816678 -0.01356772 ... -0.01252668 -0.04370638
  -0.00264896]]


In [2]:
df['query_embed'] = query_embed.tolist()
df['product_title_embed'] = product_title_embed.tolist()
df['product_description_embed'] = product_description_embed.tolist()
print(df.columns)
df.head()

In [ ]:
# a = [[1,2,3]]
# b = [[1,2,3]]
# print(cosine_similarity(a, b))

In [1]:
from sklearn.metrics.pairwise import cosine_similarity  # input to cosine_similarity should be a two dimensional array
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

value1 = [value for value in df['query_embed']]
print(value1[0])
value2 = [value for value in df['product_description_embed']]
print(len(value2))

index = 0
cosine_sim = []
a = np.zeros(len(value2))
while index < len(value1):
  temp = cosine_similarity([value1[index]], [value2[index]])
  a[0] = temp[0][0]
  cosine_sim.append([a[0]])
  index = index+1
print(type(cosine_sim[0]))
print(len(cosine_sim))
df['cosine_sim'] = cosine_sim


df.head()

In [ ]:
import numpy as np

# x = np.hstack((query_embed, product_title_embed, product_description_embed))
x = np.hstack((query_embed, product_description_embed, result))
# x = df['cosine_sim'].to_numpy()
print(x.shape)
print(x)
y = df['median_relevance'].to_numpy()
print(y.shape)
print(y)

# Create dataset

# import numpy as np

# from sklearn.datasets import make_classification
# x , y = make_classification(n_samples=400, n_features=20, n_informative=15, n_redundant=5, n_classes = 4, random_state=1)

# print(len(x[0]))
# print(x)
# print(y)

(10158, 1537)
[[ 0.00926366 -0.08032771 -0.01508144 ... -0.00685553 -0.02263863
   0.30471703]
 [-0.03399246  0.00466795 -0.04888829 ...  0.00325655 -0.02427218
   0.61230995]
 [-0.01177649 -0.00507039  0.01180198 ... -0.04584635  0.02316347
   0.6644985 ]
 ...
 [ 0.05859424 -0.02421954 -0.00885277 ...  0.00471096  0.01799529
   0.15936875]
 [ 0.00327841 -0.08907936 -0.03979023 ...  0.00744993 -0.01963961
   0.58916822]
 [-0.02924857 -0.09371798 -0.0364729  ... -0.04370638 -0.00264896
   0.73752144]]
(10158,)
[1 4 4 ... 2 1 4]


In [ ]:
from keras.utils.np_utils import to_categorical   
from sklearn.preprocessing import LabelEncoder

# # y = [1,4,3,2]
# y = y.astype(np.float)
label_encoder = LabelEncoder()
y_new = label_encoder.fit_transform(y)

print(type(y_new[0]))
print(y_new)
y_new = to_categorical(y_new, num_classes=4)
print(y_new)

<class 'numpy.int64'>
[0 3 3 ... 1 0 3]
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# a = tf.keras.utils.to_categorical([1, 2, 3, 4], num_classes=4)

In [ ]:
## IMPLEMENTING QUADRATIC WEIGHTED KAPPA IN NEURAL NETWORK

from tensorflow import keras 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import math
# Hyperparameters
num_epochs=25
batch_size=32
input_dim=len(x[0])
print(input_dim)
neurons = math.floor((2*len(x))/2)
print(neurons)

# Define custom loss

import tensorflow as tf

def kappa_loss(y_pred, y_true, y_pow=2, eps=1e-10, N=4, bsize=batch_size, name='kappa'):
  """A continuous differentiable approximation of discrete kappa loss.
      Args:
          y_pred: 2D tensor or array, [batch_size, num_classes]
          y_true: 2D tensor or array,[batch_size, num_classes]
          y_pow: int,  e.g. y_pow=2
          N: typically num_classes of the model
          bsize: batch_size of the training or validation ops
          eps: a float, prevents divide by zero
          name: Optional scope/name for op_scope.
      Returns:
          A tensor with the kappa loss."""

  with tf.name_scope(name):
    y_true = tf.cast(y_true, dtype='float')
    repeat_op = tf.cast(tf.tile(tf.reshape(tf.range(0, N), [N, 1]), [1, N]), dtype='float')
    repeat_op_sq = tf.square((repeat_op - tf.transpose(repeat_op)))
    weights = repeat_op_sq / tf.cast((N - 1) ** 2, dtype='float')

    pred_ = y_pred ** y_pow
    try:
        pred_norm = pred_ / (eps + tf.reshape(tf.reduce_sum(pred_, 1), [-1, 1]))
    except Exception:
        pred_norm = pred_ / (eps + tf.reshape(tf.reduce_sum(pred_, 1), [bsize, 1]))

    hist_rater_a = tf.reduce_sum(pred_norm, 0)
    hist_rater_b = tf.reduce_sum(y_true, 0)

    conf_mat = tf.matmul(tf.transpose(pred_norm), y_true)

    nom = tf.reduce_sum(weights * conf_mat)
    denom = tf.reduce_sum(weights * tf.matmul(
        tf.reshape(hist_rater_a, [N, 1]), tf.reshape(hist_rater_b, [1, N])) /
                          tf.cast(bsize, dtype='float'))

    return nom / (denom + eps)

# Custon loss end - a very big custom loss

# Define quadratic weighted kappa metric
    """
  Function for measuring Quadratic Weighted Kappa with scikit-learn
  
  :param y_true: The ground truth labels
  :param y_pred: The predicted labels
  
  :return The Quadratic Weighted Kappa Score (QWK)
  """
from sklearn.metrics import cohen_kappa_score
from numpy import argmax

def sklearn_qwk(y_true, y_pred) -> np.float64:
  tf.config.run_functions_eagerly(True)
  y_true_new = y_true.numpy()
  y_pred_new = y_pred.numpy()
  # print(type(y_true_new))
  y_true_new = label_encoder.inverse_transform(argmax(y_true, axis = 1))
  y_pred_new = label_encoder.inverse_transform(argmax(y_pred, axis = 1))

  return cohen_kappa_score(y_true_new, y_pred_new, weights="quadratic")

# End of quadratic weighted kappa

# model_cohen_kappa = cohen_kappa_loss(num_classes=4)
import sklearn.metrics as metrics

#define the model
model = Sequential()
model.add(Dense(neurons, input_dim = input_dim, activation = 'relu'))
model.add(Dense(4, activation = 'softmax'))

model.compile(loss = kappa_loss, optimizer = 'adam', metrics = ['accuracy', sklearn_qwk])
# model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy', sklearn_qwk])

model.summary()

1537
10158
Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 10158)             15623004  
                                                                 
 dense_19 (Dense)            (None, 4)                 40636     
                                                                 
Total params: 15,663,640
Trainable params: 15,663,640
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# try different loss keeping metric same - kappa score: 55 max - done
# try to include those 3000 train egs - max 62- done
# try less input embeds
# try more neurons in model - 59 max - done
# remove product_title_embed - bcz it seems redundant -done
# add cosine similarity score -done

history = model.fit(x, y_new, epochs=num_epochs, batch_size=batch_size, shuffle=True, verbose=1, validation_split=0.15)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py:4527: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  "Even though the `tf.config.experimental_run_functions_eagerly` "


Epoch 1/25
270/270 [==============================] - 20s 72ms/step - loss: 0.6673 - accuracy: 0.5316 - sklearn_qwk: 0.3476 - val_loss: 0.5437 - val_accuracy: 0.6115 - val_sklearn_qwk: 0.4619
Epoch 2/25
270/270 [==============================] - 20s 74ms/step - loss: 0.5125 - accuracy: 0.5814 - sklearn_qwk: 0.4898 - val_loss: 0.4939 - val_accuracy: 0.6024 - val_sklearn_qwk: 0.5147
Epoch 3/25
270/270 [==============================] - 20s 73ms/step - loss: 0.4777 - accuracy: 0.5922 - sklearn_qwk: 0.5284 - val_loss: 0.4995 - val_accuracy: 0.5925 - val_sklearn_qwk: 0.5007
Epoch 4/25
270/270 [==============================] - 20s 73ms/step - loss: 0.4254 - accuracy: 0.6273 - sklearn_qwk: 0.5775 - val_loss: 0.4657 - val_accuracy: 0.6339 - val_sklearn_qwk: 0.5382
Epoch 5/25
270/270 [==============================] - 20s 74ms/step - loss: 0.3954 - accuracy: 0.6310 - sklearn_qwk: 0.6077 - val_loss: 0.4466 - val_accuracy: 0.6181 - val_sklearn_qwk: 0.5591
Epoch 6/25
270/270 [====================

In [ ]:
print(history.history)

{'loss': [0.6673039793968201, 0.512525200843811, 0.47774723172187805, 0.42536506056785583, 0.3953503668308258, 0.39145034551620483, 0.3678653836250305, 0.36591315269470215, 0.38077229261398315, 0.34879112243652344, 0.3256534934043884, 0.31386908888816833, 0.2992907166481018, 0.29622790217399597, 0.29784858226776123, 0.2863439917564392, 0.2897628843784332, 0.2898162007331848, 0.2742638885974884, 0.27207133173942566, 0.28030097484588623, 0.2685741186141968, 0.2613339126110077, 0.2678915858268738, 0.2549949884414673], 'accuracy': [0.5316191911697388, 0.5814222693443298, 0.5921936631202698, 0.6272874474525452, 0.6309937238693237, 0.637595534324646, 0.6396803259849548, 0.6454713940620422, 0.6524206399917603, 0.6587908267974854, 0.6645818948745728, 0.674774169921875, 0.686587929725647, 0.6825341582298279, 0.6855455040931702, 0.6933055520057678, 0.6977067589759827, 0.689946711063385, 0.7008339166641235, 0.7033819556236267, 0.7047718167304993, 0.7092888355255127, 0.7125318646430969, 0.70952051